name: Test Ansible Setup Script

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-2025
        include:
          - os: macOS-latest
            shell: bash
          - os: ubuntu-latest
            shell: bash
          - os: windows-2025
            shell: wsl -- dos2unix <"$(wslpath '{0}')" | bash --noprofile --norc -euo pipefail
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WSL on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -Command "iex (Get-Content '.\wsl\install.ps1' -Raw)"

      - name: Run setup script and tests under sh
        run: |
          /usr/bin/env bash -c $(cat "./ansible/install.sh")

      - name: test Ansible installation
        run: |
          ansible --version
          ansible localhost -m ping
