name: Test Ansible Setup Script

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        include:
          - os: macOS-latest
            shell: bash
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: wsl -- dos2unix <"$(wslpath '{0}')" | bash --noprofile --norc -euo pipefail
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WSL if on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          & .\wsl\install.ps1

      - name: Verify WSL installation if on Windows
        if: runner.os == 'Windows'
        run: |
          dos2unix ./ansible/install.sh

      - name: Install Ansible
        run: |
          /bin/bash -c "$(cat ./ansible/install.sh)"
          echo $PATH
          command -v ansible

      - name: Verify Ansible installation
        run: |
          ansible --version
          ansible localhost -m ping
